version: '3'

services:
  db:
    image: mysql:5.7
    container_name: studioarquitetura
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: your-db-name
      MYSQL_USER: sa
      MYSQL_PASSWORD: sa
    volumes:
      - ./data/conf.d:/etc/mysql/conf.d
